### ISSUE TITLE
dev tracker: cpu version of halo2-fri prover

### ISSUE THREAD

**Issue by kunxian-xia** [scroll-tech/halo2#82]
- [x] trait changes in `ff`: https://github.com/kunxian-xia/ff/tree/feat/fri
   - [x] add trait for simd feature
   - [x] add trait for extension
   - [x] toolchain changes
      - [x] [ff](https://github.com/kunxian-xia/ff)
      - [x] [group](https://github.com/kunxian-xia/group)
      - [x] [pairing](https://github.com/kunxian-xia/pairing)
      - [x] [pasta_curves](https://github.com/kunxian-xia/pasta_curves)
      - [x] [poseidon](https://github.com/kunxian-xia/poseidon)
- [x] trait changes in `halo2` (https://github.com/scroll-tech/halo2/tree/feat/fri)
- [x] new trait implementors in `halo2curves` (https://github.com/kunxian-xia/halo2curves/tree/feat/fri)
   - [x] goldilocks "curve"
- [ ] basic algorithms ( ~ 2024.02.22)
    - [x] SIMD base field arithmetic (https://github.com/kunxian-xia/halo2curves/tree/feat/fri)
    - [x] extension field arithmetic
    - [ ] SIMD fft in `halo2`
    - [ ] fft of polynomial over extension field in `halo2`.
    - [ ] poseidon hasher in `halo2`
- [ ] verifier: verify plonky2 proof. (2024.02.22 ~ 2024.02.28)
   - [ ] logup verifier
   - [ ] permutation verifier
   - [ ] fri verifier
   - [ ] halo2 verifier
- [ ] prover (2024.03.01 ~ 2024.03.21)
